// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoiKgSEKO9J_afHSlCj9BGkh2SdFfetS0',
    appId: '1:258018753678:web:06f0d8e0bb08cbb8cedddf',
    messagingSenderId: '258018753678',
    projectId: 'crafty-e-commerce',
    authDomain: 'crafty-e-commerce.firebaseapp.com',
    storageBucket: 'crafty-e-commerce.firebasestorage.app',
    measurementId: 'G-4QPRWKL02N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTgPMh0RVpVR7KkWQ3FWIguO_qPwxjLmQ',
    appId: '1:258018753678:android:73f3da8b8af90d1fcedddf',
    messagingSenderId: '258018753678',
    projectId: 'crafty-e-commerce',
    storageBucket: 'crafty-e-commerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApqO7KZQvvkKZXAIeaIiw4TLRbAc9I5fc',
    appId: '1:258018753678:ios:7b9d264ace30bafdcedddf',
    messagingSenderId: '258018753678',
    projectId: 'crafty-e-commerce',
    storageBucket: 'crafty-e-commerce.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoiKgSEKO9J_afHSlCj9BGkh2SdFfetS0',
    appId: '1:258018753678:web:cfdf78ccd52297d4cedddf',
    messagingSenderId: '258018753678',
    projectId: 'crafty-e-commerce',
    authDomain: 'crafty-e-commerce.firebaseapp.com',
    storageBucket: 'crafty-e-commerce.firebasestorage.app',
    measurementId: 'G-0YYB3R0ZWF',
  );
}
